name: appmetrica
description: A Flutter plugin for AppMetrica by Yandex.
version: 0.1.3
homepage: https://github.com/modeckrus/appmetrica

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  stack_trace: ^1.10.0
  logging: ^1.0.2
  decimal: ^2.1.0

dev_dependencies:
  pigeon: '1.0.9'
  flutter_test:
    sdk: flutter
  mockito: '5.0.15'

flutter:
  plugin:
    platforms:
      android:
        package: com.yandex.appmetrica
        pluginClass: AppMetrica
      ios:
        pluginClass: YMMFAppMetrica
