// Autogenerated from Pigeon (v1.0.9), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, YMMFAppMetricaDeferredDeeplinkReasonPigeon) {
  YMMFAppMetricaDeferredDeeplinkReasonPigeonNOT_A_FIRST_LAUNCH = 0,
  YMMFAppMetricaDeferredDeeplinkReasonPigeonPARSE_ERROR = 1,
  YMMFAppMetricaDeferredDeeplinkReasonPigeonUNKNOWN = 2,
  YMMFAppMetricaDeferredDeeplinkReasonPigeonNO_REFERRER = 3,
  YMMFAppMetricaDeferredDeeplinkReasonPigeonNO_ERROR = 4,
};

typedef NS_ENUM(NSUInteger, YMMFAppMetricaDeviceIdReasonPigeon) {
  YMMFAppMetricaDeviceIdReasonPigeonUNKNOWN = 0,
  YMMFAppMetricaDeviceIdReasonPigeonNETWORK = 1,
  YMMFAppMetricaDeviceIdReasonPigeonINVALID_RESPONSE = 2,
  YMMFAppMetricaDeviceIdReasonPigeonNO_ERROR = 3,
};

typedef NS_ENUM(NSUInteger, YMMFUserProfileAttributeType) {
  YMMFUserProfileAttributeTypeBIRTH_DATE = 0,
  YMMFUserProfileAttributeTypeBOOLEAN = 1,
  YMMFUserProfileAttributeTypeCOUNTER = 2,
  YMMFUserProfileAttributeTypeGENDER = 3,
  YMMFUserProfileAttributeTypeNAME = 4,
  YMMFUserProfileAttributeTypeNOTIFICATION_ENABLED = 5,
  YMMFUserProfileAttributeTypeNUMBER = 6,
  YMMFUserProfileAttributeTypeSTRING = 7,
};

typedef NS_ENUM(NSUInteger, YMMFGenderPigeon) {
  YMMFGenderPigeonMALE = 0,
  YMMFGenderPigeonFEMALE = 1,
  YMMFGenderPigeonOTHER = 2,
  YMMFGenderPigeonUNDEFINED = 3,
};

@class YMMFAppMetricaConfigPigeon;
@class YMMFStringPigeonWrapper;
@class YMMFLocationPigeon;
@class YMMFPreloadInfoPigeon;
@class YMMFAppMetricaDeferredDeeplinkErrorPigeon;
@class YMMFAppMetricaDeferredDeeplinkPigeon;
@class YMMFAppMetricaDeferredDeeplinkParametersPigeon;
@class YMMFAppMetricaDeviceIdPigeon;
@class YMMFRevenuePigeon;
@class YMMFReceiptPigeon;
@class YMMFECommerceAmountPigeon;
@class YMMFECommerceProductPigeon;
@class YMMFECommercePricePigeon;
@class YMMFECommerceReferrerPigeon;
@class YMMFECommerceScreenPigeon;
@class YMMFECommerceCartItemPigeon;
@class YMMFECommerceOrderPigeon;
@class YMMFECommerceEventPigeon;
@class YMMFStackTraceElementPigeon;
@class YMMFErrorDetailsPigeon;
@class YMMFUserProfileAttributePigeon;
@class YMMFUserProfilePigeon;
@class YMMFReporterConfigPigeon;

@interface YMMFAppMetricaConfigPigeon : NSObject
@property(nonatomic, copy, nullable) NSString * apiKey;
@property(nonatomic, copy, nullable) NSString * appVersion;
@property(nonatomic, strong, nullable) NSNumber * crashReporting;
@property(nonatomic, strong, nullable) NSNumber * firstActivationAsUpdate;
@property(nonatomic, strong, nullable) YMMFLocationPigeon * location;
@property(nonatomic, strong, nullable) NSNumber * locationTracking;
@property(nonatomic, strong, nullable) NSNumber * logs;
@property(nonatomic, strong, nullable) NSNumber * sessionTimeout;
@property(nonatomic, strong, nullable) NSNumber * statisticsSending;
@property(nonatomic, strong, nullable) YMMFPreloadInfoPigeon * preloadInfo;
@property(nonatomic, strong, nullable) NSNumber * maxReportsInDatabaseCount;
@property(nonatomic, strong, nullable) NSNumber * nativeCrashReporting;
@property(nonatomic, strong, nullable) NSNumber * sessionsAutoTracking;
@property(nonatomic, strong, nullable) NSDictionary<NSString *, NSString *> * errorEnvironment;
@property(nonatomic, copy, nullable) NSString * userProfileID;
@property(nonatomic, strong, nullable) NSNumber * revenueAutoTracking;
@end

@interface YMMFStringPigeonWrapper : NSObject
@property(nonatomic, copy, nullable) NSString * stringPigeon;
@end

@interface YMMFLocationPigeon : NSObject
@property(nonatomic, strong, nullable) NSNumber * isNull;
@property(nonatomic, strong, nullable) NSNumber * latitude;
@property(nonatomic, strong, nullable) NSNumber * longitude;
@property(nonatomic, copy, nullable) NSString * provider;
@property(nonatomic, strong, nullable) NSNumber * altitude;
@property(nonatomic, strong, nullable) NSNumber * accuracy;
@property(nonatomic, strong, nullable) NSNumber * course;
@property(nonatomic, strong, nullable) NSNumber * speed;
@property(nonatomic, strong, nullable) NSNumber * timestamp;
@end

@interface YMMFPreloadInfoPigeon : NSObject
@property(nonatomic, strong, nullable) NSNumber * isNull;
@property(nonatomic, copy, nullable) NSString * trackingId;
@property(nonatomic, strong, nullable) NSDictionary * additionalInfo;
@end

@interface YMMFAppMetricaDeferredDeeplinkErrorPigeon : NSObject
@property(nonatomic, assign) YMMFAppMetricaDeferredDeeplinkReasonPigeon reason;
@property(nonatomic, copy, nullable) NSString * description;
@property(nonatomic, copy, nullable) NSString * message;
@end

@interface YMMFAppMetricaDeferredDeeplinkPigeon : NSObject
@property(nonatomic, copy, nullable) NSString * deeplink;
@property(nonatomic, strong, nullable) YMMFAppMetricaDeferredDeeplinkErrorPigeon * error;
@end

@interface YMMFAppMetricaDeferredDeeplinkParametersPigeon : NSObject
@property(nonatomic, strong, nullable) NSDictionary * parameters;
@property(nonatomic, strong, nullable) YMMFAppMetricaDeferredDeeplinkErrorPigeon * error;
@end

@interface YMMFAppMetricaDeviceIdPigeon : NSObject
@property(nonatomic, copy, nullable) NSString * deviceId;
@property(nonatomic, assign) YMMFAppMetricaDeviceIdReasonPigeon errorReason;
@end

@interface YMMFRevenuePigeon : NSObject
@property(nonatomic, copy, nullable) NSString * price;
@property(nonatomic, copy, nullable) NSString * currency;
@property(nonatomic, strong, nullable) NSNumber * quantity;
@property(nonatomic, copy, nullable) NSString * productId;
@property(nonatomic, copy, nullable) NSString * payload;
@property(nonatomic, strong, nullable) YMMFReceiptPigeon * receipt;
@property(nonatomic, copy, nullable) NSString * transactionId;
@end

@interface YMMFReceiptPigeon : NSObject
@property(nonatomic, strong, nullable) NSNumber * isNull;
@property(nonatomic, copy, nullable) NSString * data;
@property(nonatomic, copy, nullable) NSString * signature;
@end

@interface YMMFECommerceAmountPigeon : NSObject
@property(nonatomic, strong, nullable) NSNumber * isNull;
@property(nonatomic, copy, nullable) NSString * amount;
@property(nonatomic, copy, nullable) NSString * currency;
@end

@interface YMMFECommerceProductPigeon : NSObject
@property(nonatomic, strong, nullable) NSNumber * isNull;
@property(nonatomic, copy, nullable) NSString * sku;
@property(nonatomic, copy, nullable) NSString * name;
@property(nonatomic, strong, nullable) NSArray<NSString *> * categoriesPath;
@property(nonatomic, strong, nullable) NSDictionary<NSString *, NSString *> * payload;
@property(nonatomic, strong, nullable) YMMFECommercePricePigeon * actualPrice;
@property(nonatomic, strong, nullable) YMMFECommercePricePigeon * originalPrice;
@property(nonatomic, strong, nullable) NSArray<NSString *> * promocodes;
@end

@interface YMMFECommercePricePigeon : NSObject
@property(nonatomic, strong, nullable) NSNumber * isNull;
@property(nonatomic, strong, nullable) YMMFECommerceAmountPigeon * fiat;
@property(nonatomic, strong, nullable) NSArray<YMMFECommerceAmountPigeon *> * internalComponents;
@end

@interface YMMFECommerceReferrerPigeon : NSObject
@property(nonatomic, strong, nullable) NSNumber * isNull;
@property(nonatomic, copy, nullable) NSString * type;
@property(nonatomic, copy, nullable) NSString * identifier;
@property(nonatomic, strong, nullable) YMMFECommerceScreenPigeon * screen;
@end

@interface YMMFECommerceScreenPigeon : NSObject
@property(nonatomic, strong, nullable) NSNumber * isNull;
@property(nonatomic, copy, nullable) NSString * name;
@property(nonatomic, strong, nullable) NSArray<NSString *> * categoriesPath;
@property(nonatomic, copy, nullable) NSString * searchQuery;
@property(nonatomic, strong, nullable) NSDictionary<NSString *, NSString *> * payload;
@end

@interface YMMFECommerceCartItemPigeon : NSObject
@property(nonatomic, strong, nullable) NSNumber * isNull;
@property(nonatomic, strong, nullable) YMMFECommerceProductPigeon * product;
@property(nonatomic, copy, nullable) NSString * quantity;
@property(nonatomic, strong, nullable) YMMFECommercePricePigeon * revenue;
@property(nonatomic, strong, nullable) YMMFECommerceReferrerPigeon * referrer;
@end

@interface YMMFECommerceOrderPigeon : NSObject
@property(nonatomic, strong, nullable) NSNumber * isNull;
@property(nonatomic, copy, nullable) NSString * identifier;
@property(nonatomic, strong, nullable) NSArray<YMMFECommerceCartItemPigeon *> * items;
@property(nonatomic, strong, nullable) NSDictionary<NSString *, NSString *> * payload;
@end

@interface YMMFECommerceEventPigeon : NSObject
@property(nonatomic, copy, nullable) NSString * eventType;
@property(nonatomic, strong, nullable) YMMFECommerceAmountPigeon * amount;
@property(nonatomic, strong, nullable) YMMFECommerceCartItemPigeon * cartItem;
@property(nonatomic, strong, nullable) YMMFECommerceOrderPigeon * order;
@property(nonatomic, strong, nullable) YMMFECommercePricePigeon * price;
@property(nonatomic, strong, nullable) YMMFECommerceProductPigeon * product;
@property(nonatomic, strong, nullable) YMMFECommerceReferrerPigeon * referrer;
@property(nonatomic, strong, nullable) YMMFECommerceScreenPigeon * screen;
@end

@interface YMMFStackTraceElementPigeon : NSObject
@property(nonatomic, copy, nullable) NSString * className;
@property(nonatomic, copy, nullable) NSString * fileName;
@property(nonatomic, strong, nullable) NSNumber * line;
@property(nonatomic, strong, nullable) NSNumber * column;
@property(nonatomic, copy, nullable) NSString * methodName;
@end

@interface YMMFErrorDetailsPigeon : NSObject
@property(nonatomic, strong, nullable) NSNumber * isNull;
@property(nonatomic, copy, nullable) NSString * exceptionClass;
@property(nonatomic, copy, nullable) NSString * message;
@property(nonatomic, copy, nullable) NSString * dartVersion;
@property(nonatomic, strong, nullable) NSArray<YMMFStackTraceElementPigeon *> * backtrace;
@end

@interface YMMFUserProfileAttributePigeon : NSObject
@property(nonatomic, copy, nullable) NSString * key;
@property(nonatomic, strong, nullable) NSNumber * doubleValue;
@property(nonatomic, copy, nullable) NSString * stringValue;
@property(nonatomic, strong, nullable) NSNumber * boolValue;
@property(nonatomic, strong, nullable) NSNumber * year;
@property(nonatomic, strong, nullable) NSNumber * month;
@property(nonatomic, strong, nullable) NSNumber * day;
@property(nonatomic, strong, nullable) NSNumber * age;
@property(nonatomic, assign) YMMFGenderPigeon genderValue;
@property(nonatomic, strong, nullable) NSNumber * ifUndefined;
@property(nonatomic, strong, nullable) NSNumber * reset;
@property(nonatomic, assign) YMMFUserProfileAttributeType type;
@end

@interface YMMFUserProfilePigeon : NSObject
@property(nonatomic, strong, nullable) NSArray<YMMFUserProfileAttributePigeon *> * attributes;
@end

@interface YMMFReporterConfigPigeon : NSObject
@property(nonatomic, copy, nullable) NSString * apiKey;
@property(nonatomic, strong, nullable) NSNumber * sessionTimeout;
@property(nonatomic, strong, nullable) NSNumber * statisticsSending;
@property(nonatomic, strong, nullable) NSNumber * maxReportsInDatabaseCount;
@property(nonatomic, copy, nullable) NSString * userProfileID;
@property(nonatomic, strong, nullable) NSNumber * logs;
@end

/// The codec used by YMMFAppMetricaConfigConverterPigeon.
NSObject<FlutterMessageCodec> *YMMFAppMetricaConfigConverterPigeonGetCodec(void);

@protocol YMMFAppMetricaConfigConverterPigeon
- (nullable NSString *)toJsonConfig:(YMMFAppMetricaConfigPigeon *)config error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void YMMFAppMetricaConfigConverterPigeonSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<YMMFAppMetricaConfigConverterPigeon> *_Nullable api);

/// The codec used by YMMFAppMetricaPigeon.
NSObject<FlutterMessageCodec> *YMMFAppMetricaPigeonGetCodec(void);

@protocol YMMFAppMetricaPigeon
- (void)activateConfig:(YMMFAppMetricaConfigPigeon *)config error:(FlutterError *_Nullable *_Nonnull)error;
- (void)activateReporterConfig:(YMMFReporterConfigPigeon *)config error:(FlutterError *_Nullable *_Nonnull)error;
- (void)touchReporterApiKey:(NSString *)apiKey error:(FlutterError *_Nullable *_Nonnull)error;
- (nullable NSNumber *)getLibraryApiLevelWithError:(FlutterError *_Nullable *_Nonnull)error;
- (nullable NSString *)getLibraryVersionWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)resumeSessionWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)pauseSessionWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportAppOpenDeeplink:(YMMFStringPigeonWrapper *)deeplink error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportErrorError:(YMMFErrorDetailsPigeon *)error message:(YMMFStringPigeonWrapper *)message error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportErrorWithGroupGroupId:(NSString *)groupId error:(YMMFErrorDetailsPigeon *)error message:(YMMFStringPigeonWrapper *)message error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportUnhandledExceptionError:(YMMFErrorDetailsPigeon *)error error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportEventWithJsonEventName:(NSString *)eventName attributesJson:(YMMFStringPigeonWrapper *)attributesJson error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportEventEventName:(NSString *)eventName error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportReferralUrlReferralUrl:(NSString *)referralUrl error:(FlutterError *_Nullable *_Nonnull)error;
- (void)requestDeferredDeeplinkWithCompletion:(void(^)(YMMFAppMetricaDeferredDeeplinkPigeon *_Nullable, FlutterError *_Nullable))completion;
- (void)requestDeferredDeeplinkParametersWithCompletion:(void(^)(YMMFAppMetricaDeferredDeeplinkParametersPigeon *_Nullable, FlutterError *_Nullable))completion;
- (void)requestAppMetricaDeviceIDWithCompletion:(void(^)(YMMFAppMetricaDeviceIdPigeon *_Nullable, FlutterError *_Nullable))completion;
- (void)sendEventsBufferWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)setLocationLocation:(YMMFLocationPigeon *)location error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setLocationTrackingEnabled:(NSNumber *)enabled error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setStatisticsSendingEnabled:(NSNumber *)enabled error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setUserProfileIDUserProfileID:(YMMFStringPigeonWrapper *)userProfileID error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportUserProfileUserProfile:(YMMFUserProfilePigeon *)userProfile error:(FlutterError *_Nullable *_Nonnull)error;
- (void)putErrorEnvironmentValueKey:(NSString *)key value:(YMMFStringPigeonWrapper *)value error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportRevenueRevenue:(YMMFRevenuePigeon *)revenue error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportECommerceEvent:(YMMFECommerceEventPigeon *)event error:(FlutterError *_Nullable *_Nonnull)error;
- (void)handlePluginInitFinishedWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void YMMFAppMetricaPigeonSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<YMMFAppMetricaPigeon> *_Nullable api);

/// The codec used by YMMFReporterPigeon.
NSObject<FlutterMessageCodec> *YMMFReporterPigeonGetCodec(void);

@protocol YMMFReporterPigeon
- (void)sendEventsBufferApiKey:(NSString *)apiKey error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportEventApiKey:(NSString *)apiKey eventName:(NSString *)eventName error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportEventWithJsonApiKey:(NSString *)apiKey eventName:(NSString *)eventName attributesJson:(YMMFStringPigeonWrapper *)attributesJson error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportErrorApiKey:(NSString *)apiKey error:(YMMFErrorDetailsPigeon *)error message:(YMMFStringPigeonWrapper *)message error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportErrorWithGroupApiKey:(NSString *)apiKey groupId:(NSString *)groupId error:(YMMFErrorDetailsPigeon *)error message:(YMMFStringPigeonWrapper *)message error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportUnhandledExceptionApiKey:(NSString *)apiKey error:(YMMFErrorDetailsPigeon *)error error:(FlutterError *_Nullable *_Nonnull)error;
- (void)resumeSessionApiKey:(NSString *)apiKey error:(FlutterError *_Nullable *_Nonnull)error;
- (void)pauseSessionApiKey:(NSString *)apiKey error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setStatisticsSendingApiKey:(NSString *)apiKey enabled:(NSNumber *)enabled error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setUserProfileIDApiKey:(NSString *)apiKey userProfileID:(YMMFStringPigeonWrapper *)userProfileID error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportUserProfileApiKey:(NSString *)apiKey userProfile:(YMMFUserProfilePigeon *)userProfile error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportRevenueApiKey:(NSString *)apiKey revenue:(YMMFRevenuePigeon *)revenue error:(FlutterError *_Nullable *_Nonnull)error;
- (void)reportECommerceApiKey:(NSString *)apiKey event:(YMMFECommerceEventPigeon *)event error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void YMMFReporterPigeonSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<YMMFReporterPigeon> *_Nullable api);

NS_ASSUME_NONNULL_END
